---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: text
  name: ingress-text
  label: Ingress
- type: text
  name: excerpt
  label: Excerpt
  description: Short description
- type: file
  name: image
  label: Image
- type: field_group_list
  name: links
  label: Links
  fields:
  - type: text
    name: title
    label: title
  - type: text
    name: url
    label: url
- type: field_group_list
  name: contact
  label: Contact information
  fields:
  - type: text
    name: name
    label: name
  - type: file
    name: image
    label: image
  - type: text
    name: text
    label: text
  - type: text
    name: mail
    label: mail
  - type: text
    name: url
    label: url
  - type: text
    name: organisation
    label: organisation
  - type: text
    name: organisation-link
    label: organisation-link
- type: text
  name: chat
  label: Chat channel
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: categories
  type: tag_list
  default: []
  label: Categories
  description: Add references to groups and events here (use the value of the translation
    reference field)
- name: lang
  type: select
  default: sv
  config:
    required: true
    options:
    - sv
    - en
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Language
- type: text
  name: ref
  label: Translation reference
- type: datetime
  name: date
  label: Date
  hidden: true
  config:
    required: true
  default: now
pages:
- _posts/2020-06-08-digifysiska-vardkontakter.md
